### ISSUE TITLE
Words overlapping logo on the Android notes 5 mobile

### ISSUE THREAD

**Issue by wlongdonstudio** [socialveo/socialveo-issues-tracking#38]
https://www.dropbox.com/s/dpcnv131r140r5g/Screenshot_20161227-220518.png?dl=0

https://www.dropbox.com/s/l343o3j885pfa3m/Screenshot_20161227-220528.jpg?dl=0

**Comment by mervick** [comment]
Fixed

**Comment by wlongdonstudio** [comment]
Once you log in it's still not aligned the icons for mails, chat, add friend etc is not aligned to. he left with very thing else

https://www.dropbox.com/s/7z05fi20ouxo489/Screenshot_20161228-115139.png?dl=0
